{% set version = "5.8.0" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}
{% set build = 3 %}

package:
  name: paraview
  version: {{ version }}

source:
  url: http://paraview.org/files/v{{ maj_min }}/ParaView-v5.8.0.tar.gz
  md5: 8151ed24eeeae5bc8ba038bb544eb409

build:
  number: {{ build }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  skip: true  # [win and vc<14]
  skip: true  # [py2k]
  run_exports:
    - {{ pin_subpackage('paraview', max_pin='x.x') }}
  string: "{{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxt-devel') }}           # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
    - make                               # [linux]
  host:
    - python
    # need to list hdf5 twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*  # [mpi != 'nompi']
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - libpng
    - jpeg
    - libtiff
    - libxml2
    - zlib
    - freetype
    - libprotobuf
    - lz4-c
    - expat
    - libnetcdf
    - glew
    - double-conversion
    - jsoncpp
    - xz
    - cgns
    - qt
    - boost-cpp
    - pugixml
    - libtheora
  run:
    - python
    - numpy
    - matplotlib-base
    - twisted
    # hdf5 >=1.10.4 has run_exports
    - hdf5
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']

test:
  imports:
    - paraview
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.cpexport
    - paraview.cpstate
    - paraview.lookuptable
    - paraview.numeric
    - paraview.numpy_support
    - paraview.python_view
    - paraview.cpstate
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - python -c "from paraview.simple import VisItNek5000Reader"
    # https://gitlab.kitware.com/paraview/paraview/issues/19645
    - pvpython --version  # [not osx]

about:
   home: http://www.paraview.org
   license: BSD 3-Clause
   license_file: Copyright.txt
   summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - bgruening
    - jschueller
